add_newline = false

[directory]
truncation_length = 18
fish_style_pwd_dir_length = 18
truncation_symbol = "â€¦/"

[git_branch]
symbol = "ğŸŒ± "

[git_state]
format = "[\\($state( $progress_current of $progress_total)\\)]($style) "
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_commit]
commit_hash_length = 7
tag_symbol = "ğŸ· "

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[package]
disabled = true

[nodejs]
disabled = true

[swift]
disabled = true

[php]
disabled = true

[aws]
disabled = true

[status]
symbol = "ğŸ’£ "
format = "\\[$symbol\\] "
disabled = true

